server:
  port: 9527
spring:
  application:
    name: springCloud-gateway-9527
  cloud:
    gateway:
      routes:
        - id: springCloud-provider-8001 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001   #匹配后提供服务的路由地址
          predicates:
            - Path=/dept/**   #断言,路径相匹配的进行路由

eureka:
  instance:
    prefer-ip-address: true
    hostname: cloud-gate9527
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka8002:8002/eureka/, http://eureka8003:8003/eureka/
