spring:
  application:
    name: ProviderHystrix8004  #微服务名称，对外暴漏的微服务名称，十分重要
  #配置数据源
  datasource:
    #配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    name: datasource
    #驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库url，数据库名称根据自己的定
    url: jdbc:mysql://localhost:3307/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai

    username: root
    password: Jason20040903
    #通过别名的方式配置扩展插件,stat日志用的filter
    filters: stat
    #最大连接池数量
    maxActive: 20
    #初始化时建立物理连接的个数
    initialSize: 5
    #获取连接时最大等待时间，单位毫秒
    maxWait: 60000
    #最小连接池数量，已经不再使用了
    minIdle: 1
    #每60秒运行一次空闲连接回收器
    timeBetweenEvictionRunsMillis: 60000
    #池中的连接空闲30分钟后被回收,默认值就是30分钟
    minEvictableIdleTimeMillis: 1800000
    #验证连接是否可用，使用的SQL语句
    validationQuery: select 1 from dual
    #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
    testWhileIdle: true
    #借出连接时不要测试，否则很影响性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    #是否缓存preparedStatement，也就是PSCache;PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
    poolPreparedStatements: true
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
    maxOpenPreparedStatements: -1

server:
  port: 8004
########################################### Spring cloud 自定义服务名称和 ip 地址###############################################
eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      #defaultZone: http://eureka7001:7001/eureka  #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）
      defaultZone: http://eureka8002:8002/eureka/, http://eureka8003:8003/eureka/  #将服务注册到 Eureka 集群
  instance:
    instance-id: spring-cloud-provider-8004 #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址
#####################spring cloud 使用 Spring Boot actuator 监控完善信息###########################################
# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * 在yaml 文件属于关键字，所以需要加引号

info:
  app:
    name: node16-boot-actuator
    port: 8004
    version: 1.0.0
    author: cicada

mybatis:
  type-aliases-package: codeofwhite.hystrix.entity
  mapper-locations: classpath:mapper/*.xml